//! Compile-time shared template tests.
//!
//! This file includes code generated by `build.rs` that:
//! 1. Uses `template!` to compile every shared test case at **compile time**
//!    (catching any parsing/type-checking issues in the proc macro).
//! 2. Renders each compiled template at **runtime** and compares output
//!    to the expected value from the shared TOML fixture.
//! 3. Also renders the same template via `Template::from_source()` and
//!    asserts that both paths produce identical output (parity check).
//!
//! Tests using file includes, env: blocks, or `expected_error` are excluded
//! since they can't be expressed as `template!` invocations.

include!(concat!(env!("OUT_DIR"), "/shared_compile_time_gen.rs"));
