//! Test-only crate: `tests/shared_compile_time.rs` includes `template!`
//! invocations generated by `build.rs` from the shared TOML fixtures, so the
//! proc macro compiles every shared case at build time without shipping the
//! generator (and its toml build-dependency) in the published md-tmpl crate.
